### ISSUE TITLE
Clean Core Installation and Clean DAM Installation Error

### ISSUE THREAD

**Issue by drupalshift** [treolabs/treodam#44]
I'm installing Core from composer and it's working as soon as I add DAM I can't log in anymore with error 500 here is the log file 

```[2020-05-05 09:58:01] Espo.ERROR: Uncaught Exception Espo\Core\Exceptions\Error: "Service 'Entity' was not found" at /shared/httpd/treodam/htdocs/vendor/treolabs/treocore/app/Treo/Core/ServiceFactory.php line 146 {"exception":"[object] (Espo\\Core\\Exceptions\\Error(code: 500): Service 'Entity' was not found at /shared/httpd/treodam/htdocs/vendor/treolabs/treocore/app/Treo/Core/ServiceFactory.php:146)"} []```

**Comment by rratsun** [comment]
Fix at 1.2.4
